version: "2"

services:
  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/arnaudlacour/katacoda.git
      - SERVER_PROFILE_PATH=licenses/pingfederate
      - SERVER_PROFILE_PARENT=BASE
      - SERVER_PROFILE_BASE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_BASE_PATH=baseline/pingfederate
      - VERBOSE=false
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - SERVER_PROFILE_PARENT=MONITORING
      - SERVER_PROFILE_MONITORING_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_MONITORING_PATH=monitoring/pingdirectory/jolokia
      - SERVER_PROFILE_MONITORING_PARENT=LICENSE
      - SERVER_PROFILE_LICENSE_URL=https://github.com/arnaudlacour/katacoda.git
      - SERVER_PROFILE_LICENSE_PATH=licenses/pingdirectory
    networks:
      - pingnet
                    
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8443:8443
    networks:
      - pingnet

networks:
    pingnet:
